In [14]:
#q1
import numpy as np
A = np.array([[4.0,-2.0,1.0],[1.0,1.0,1.0],[9.0,3.0,1.0]])
b = np.array([[8.0],[-13.0],[3.0]])
def fwd_gauss(Ab):
    MAb = Ab.copy()
    [nr_Ab,nc_Ab] = Ab.shape
    for r in range(0,nr_Ab):
        #normalizing row r
        k = MAb[r,r]
        MAb[r,:] = (1/k) * MAb[r,:]
        # clear column r
        if(r != nr_Ab-1):
            for i in range(r+1,nr_Ab):
                row_factor = 1/MAb[i,r]
                MAb[i,:] = (row_factor) * MAb[i,:]
                MAb[i,:] = MAb[i,:] - MAb[r,:]
    return MAb
Ab = np.append(A,b,axis=1)
print('Ab = ')
print(Ab)
GAb = fwd_gauss(Ab)
print('GAb = ')
print(GAb)

Ab = 
[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]
GAb = 
[[  1.    -0.5    0.25   2.  ]
 [  0.     1.     0.5  -10.  ]
 [ -0.    -0.     1.   -12.  ]]


In [15]:
#q2
import numpy as np
M = [[3.0, 0.0, 2.0], [2.0, 0.0, -2.0], [0.0, 1.0, 1.0]]
def inverse(a):
    n = len(a) 
    P = [[0.0 for i in range(len(a))] for j in range(len(a))]
    for i in range(3):
        for j in range(3):
            P[j][j] = 1.01
    for i in range(len(a)):
        a[i].extend(P[i])
    for k in range(n):
        if abs(a[k][k]) < 1.0e-12:
            for i in range(k+1, n):
                if abs(a[i][k]) > abs(a[k][k]):
                    for j in range(k, 2*n):
                        a[k][j], a[i][j] = a[i][j], a[k][j] #swapping of rows
                    break
        pivot = a[k][k] #defining the pivot
        if pivot == 0: #checking if matrix is invertible
            print("This matrix is not invertible.")
            return
        else:
            for j in range(k, 2*n): #index of columns of the pivot row
                a[k][j] /= pivot
            for i in range(n): #index the subtracted rows
                if i == k or a[i][k] == 0: continue
                factor = a[i][k]
                for j in range(k, 2*n): #index the columns for subtraction
                    a[i][j] -= factor * a[k][j]
    for i in range(len(a)): 
        for j in range(n, len(a[0])):
            round_off = np.round_(a[i][j],decimals=1)
            print(round_off, end = " ")
        print()
print("Inverse of a Matrix")
inverse(M)

Inverse of a Matrix
0.2 0.2 0.0 
-0.2 0.3 1.0 
0.2 -0.3 -0.0 
